services:
  app:
    build: .
    # image: app:latest
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - "5000:5000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"